#!/bin/sh
tty=${PWD##*-}
if [ -x /sbin/getty ]; then
	# busybox
	GETTY=getty
elif [ -x /sbin/agetty ]; then
	# util-linux
	GETTY=agetty
	GETTY_ARGS="-a live --noclear"
fi
exec setsid $GETTY $GETTY_ARGS $tty 38400 linux
